### ISSUE TITLE
How to gracefully fail?

### ISSUE THREAD

**Issue by Jonyorker** [karlludwigweise/git-subtree#2]
Hi,

I've been using this action in our team for a while with great success.

Demands have changed a bit, and I need a way to pipe in a different branch for subtree, and if it fails, to revert to another.

is it possible to modify this to offer a graceful second option?

Currently, if it doesn't find the branch, it outputs: "fatal: couldn't find remote ref"

Ideally, if I could supply a fallback-position option, that would be slick.

**Comment by karlludwigweise** [comment]
Hi @Jonyorker,

I saw you closed this issue and a PR already. You probably went with your own action by now.

That's actually what I would have proposed in this case. A fallback option would add complexity for a niche requirement to this otherwise very simple action.

I would also like to add that failing in case of a missing branch is by design.

My two cents on the implementation of a fallback: I would evaluate if the branch exists inside your workflow and call the action with the correct branch name as a parameter.

Thank you for taking the time to draft a PR along with your request!
